### ISSUE TITLE
Update to use UTC DateTime instead of Local DateTime

### ISSUE THREAD

**Issue by Bo-Jangles** [teshiba/AoE2.netDesktop#39]
**Describe the bug**
One of the test cases is failing because it is time zone dependent: PlotTest in PlayerRateFormsPlotTests.cs 

**To Reproduce**
Run the above test in a time zone other than GMT+9.

**Screenshots**
![before](https://user-images.githubusercontent.com/108393338/176746864-a9846427-e1f3-41ec-a6c1-8381b887cfe6.png)

**Additional context**
Several changes are required to address time zone dependency:
- DateTimeOffset.FromUnixTimeSeconds() returns a UTC date so using the UtcDateTime property would make the code timezone independent. 
- Similarly, the DateTime.Now.ToUniversalTime() method should be used instead of the DateTime.Now.ToLocalTime() method.

**Comment by teshiba** [comment]
@Bo-Jangles 
Could you run the test on the 'develop' branch?

I recently found this fails on the GitHub Actions environment.
On develop branch, I've fixed the issue and pushed the commits.

Thanks for reporting about the 'unit test' as well!
Especially, it is hard to find localizing issues.

There are the latest codes on develop branch!
If you could report unit test issues, please check it out!

I'll check PR #40 later as well.

**Comment by Bo-Jangles** [comment]
I've run the test on the develop branch. It passes! I will use this branch going forward.

As for PR #40 I think that my change to the following file is incorrect because local time is required here.
AoE2.netDesktop/LibAoE2Net/Functions/MatchExt.cs

This PR can be ignored because it was based on outdated code.
